# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/tela_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fmTelaInicial(object):
    def setupUi(self, fmTelaInicial):
        fmTelaInicial.setObjectName("fmTelaInicial")
        fmTelaInicial.resize(1280, 720)
        self.label = QtWidgets.QLabel(fmTelaInicial)
        self.label.setGeometry(QtCore.QRect(60, 70, 280, 61))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(fmTelaInicial)
        self.label_2.setGeometry(QtCore.QRect(920, 70, 290, 61))
        self.label_2.setObjectName("label_2")
        self.lbPecasAprovadas = QtWidgets.QLabel(fmTelaInicial)
        self.lbPecasAprovadas.setGeometry(QtCore.QRect(110, 160, 160, 61))
        self.lbPecasAprovadas.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.lbPecasAprovadas.setObjectName("lbPecasAprovadas")
        self.lbPecasReprovadas = QtWidgets.QLabel(fmTelaInicial)
        self.lbPecasReprovadas.setGeometry(QtCore.QRect(980, 160, 160, 61))
        self.lbPecasReprovadas.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.lbPecasReprovadas.setObjectName("lbPecasReprovadas")
        self.txaInformacoes = QtWidgets.QTextEdit(fmTelaInicial)
        self.txaInformacoes.setGeometry(QtCore.QRect(398, 370, 460, 191))
        self.txaInformacoes.setObjectName("txaInformacoes")
        self.label_3 = QtWidgets.QLabel(fmTelaInicial)
        self.label_3.setGeometry(QtCore.QRect(538, 330, 160, 40))
        self.label_3.setObjectName("label_3")
        self.btZerar = QtWidgets.QPushButton(fmTelaInicial)
        self.btZerar.setGeometry(QtCore.QRect(400, 600, 130, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btZerar.setFont(font)
        self.btZerar.setObjectName("btZerar")
        self.btReset = QtWidgets.QPushButton(fmTelaInicial)
        self.btReset.setGeometry(QtCore.QRect(728, 600, 130, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btReset.setFont(font)
        self.btReset.setObjectName("btReset")
        self.btConfigurar = QtWidgets.QPushButton(fmTelaInicial)
        self.btConfigurar.setGeometry(QtCore.QRect(20, 600, 170, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btConfigurar.setFont(font)
        self.btConfigurar.setObjectName("btConfigurar")

        self.retranslateUi(fmTelaInicial)
        QtCore.QMetaObject.connectSlotsByName(fmTelaInicial)

    def retranslateUi(self, fmTelaInicial):
        _translate = QtCore.QCoreApplication.translate
        fmTelaInicial.setWindowTitle(_translate("fmTelaInicial", "Form"))
        self.label.setText(_translate("fmTelaInicial", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Peças Aprovadas</span></p></body></html>"))
        self.label_2.setText(_translate("fmTelaInicial", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Peças Reprovadas</span></p></body></html>"))
        self.lbPecasAprovadas.setText(_translate("fmTelaInicial", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">0</span></p></body></html>"))
        self.lbPecasReprovadas.setText(_translate("fmTelaInicial", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">0</span></p></body></html>"))
        self.label_3.setText(_translate("fmTelaInicial", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Informações</span></p></body></html>"))
        self.btZerar.setText(_translate("fmTelaInicial", "ZERAR"))
        self.btReset.setText(_translate("fmTelaInicial", "RESET"))
        self.btConfigurar.setText(_translate("fmTelaInicial", "CONFIGURAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fmTelaInicial = QtWidgets.QWidget()
    ui = Ui_fmTelaInicial()
    ui.setupUi(fmTelaInicial)
    fmTelaInicial.show()
    sys.exit(app.exec_())
